changing url from which remotesyslog2 is pulled from
masschallenge/opsworks-web-python pull request #5
Opened 2018-03-27 20:01 UTC by shanbady

This fixes the "remote_syslog2" package which is required for papertrail based logging on opsworks servers.

To test this:

1 - Go to a test opsworks stack and go to the "stack settings" make sure the branch/revision for the custom cookbooks is set to the current master.
<img width="786" alt="screen shot 2018-03-27 at 3 37 58 pm" src="https://user-images.githubusercontent.com/196425/37991686-d1d18782-31d7-11e8-92bb-016982803d27.png">

2 - run the "update custom cookbooks" command on the stack to make sure it has the latest master recipes.
3 -  once this completes run the "Execute recipes" command with "remote_syslog2::install" as the command.

<img width="536" alt="screen shot 2018-03-27 at 3 40 29 pm" src="https://user-images.githubusercontent.com/196425/37990891-956b25de-31d5-11e8-8432-0e18a0bbdff7.png">

4 - note that this fails.

5 - go back to the stack settings and switch the branch to AC-5303.

6 - go through steps 2 and 3 again.

7 - note that this succeeds.

Once this gets merged in we will need to add the remote_syslog2::install and remote_syslog2::service recipes to all the stacks just before the opsworks deploy recipe.

2018-03-28 07:56 UTC, yotammanor commented
@shanbady can't we just upgrade to a newer version of remote_syslog?

2018-03-28 08:07 UTC, yotammanor requested changes
I tried to follow the steps described, but the recipe succeeded on master. See https://console.aws.amazon.com/opsworks/home?region=us-east-1#/stack/be1aff02-9fb5-4c7c-9241-d515f8f5f816/deployments/55d1873e-71f1-41fe-b693-b1ffc2ba38a7

2018-03-28 08:17 UTC, yotammanor commented
@shanbady 
I am able to see logs being written to papertrail https://papertrailapp.com/systems/673542122/events , but I am not seeing all log events (I tried to get into https://test2.masschallenge.org/judge_feedback_reports/ without REVIEWER permissions so I got a 404, then I added it to my user in the admin, then went back in and saw the page. When I did this I saw deprecation warnings and the 403 error, but I didn't see the logger.info message that was declared in `mc/permission_checks.py:99` and was definitely triggered).

Seems like this is still a problem, so mentioning that as well

2018-03-30 15:59 UTC, shanbady commented
@yotammanor - there was an issue with my testing instructions. I just updated it with the correct steps.

2018-04-01 08:18 UTC, yotammanor commented
@shanbady I tried to follow the instructions again, and test2 still succeeds on master. I even ssh-ed into test2, and tried to `wget` the original `tar.gz` file from github and it succeeded. 

The new link also succeeds, and deployment works with opsworks-web-python pointing at AC-5303, so if you think this is better to keep the link pointing to our own repo, then I'm willing to approve. I think that in the long term it's better that it points at github, so we can update versions more easily. But it's your call.

The issues with seeing the django logs themselves persist as described above. This is probably a different PR/ticket, but noting that anyhow.

2018-04-01 08:19 UTC, yotammanor reviewed
@shanbady 
I am able to see logs being written to papertrail https://papertrailapp.com/systems/673542122/events , but I am not seeing all log events (I tried to get into https://test2.masschallenge.org/judge_feedback_reports/ without REVIEWER permissions so I got a 404, then I added it to my user in the admin, then went back in and saw the page. When I did this I saw deprecation warnings and the 403 error, but I didn't see the logger.info message that was declared in `mc/permission_checks.py:99` and was definitely triggered).

Seems like this is still a problem, so mentioning that as well

2018-04-02 19:25 UTC, shanbady commented
@yotammanor i am seeing logs for test 2 when searching for messages associated with the ip of the running instance (https://papertrailapp.com/systems/673542122/events?q=54.211.237.251) . If you go to that link and hit the judge_feedback_reports view you should see some logging (in my case ``` django.request[17136]: WARNING Forbidden (Permission denied): /judge_feedback_reports/ ```)

2018-04-03 08:49 UTC, yotammanor commented
@shanbady I saw this error too. What I expected to see and did not see is one of the following:
```

CLEARANCE_LOGGER_FAILED_INSUFFICIENT_CLEARANCE_MSG = (
        CLEARANCE_LOGGER_FAILURE_BASE_MSG + "Reason: Insufficient privileges."
)
CLEARANCE_LOGGER_SUCCESS_MSG = (
    "clearance_check success: {user} attempted to access "
    "{program_family} related data that requires a clearance of "
    "{level}, and was granted access.")
```
(see `mc/managers/clearance_manager.py` for declaration and see `mc/permission_checks.py` for invocation)

2018-04-03 20:38 UTC, shanbady commented
@yotammanor the JudgeFeedbackReports view appears to call "feedback_permissions_check" which in turn checks "is_in_group" to then raise a 403. Where are you seeing that it hits that log line on access?

2018-04-04 09:10 UTC, yotammanor commented
@shanbady again, if you give the accessing user the REVIEWER permissions, then those lines should be accessed, and log a failure or a success. So at least on line from permission_checks should be seen, and you can see this behaviour locally.

2018-04-04 14:25 UTC, shanbady commented
@yotammanor i did this locally and im not seeing a log line for either. if i masquerade as a user i see the masquerading getting logged and that shows up in papertrail. is there some other condition in your local that gets that line to show?

2018-04-04 18:47 UTC, yotammanor approved these changes

2018-04-04 18:48 UTC, merged